theme: jekyll-theme-architect

title: Rodrigo Bonifácio

description: I am an assistant professor at the Computer Science Department, University of Brasília and a member of the Software Productivity Group, led by Prof. Paulo Borba. Currently I am spending a sabbatical year at the University of Paderborn (working under the supervision of Prof. Eric Bodden). My research focuses on understanding the typical usage of programming language features, refactoring towards language evolution, software architecture and modularity, and software product lines.

I have B.S. and M.S. degrees in Computer Science from Federal University of Paraíba, respectively in João Pessoa and Campina Grande, and a Ph.D. in Computer Science from Federal University of Pernambuco, in Recife.

show_downloads: false